import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "LOL DUO",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
        <link rel="icon" href="Rank=Challenger.png" />
      <body className={`${inter.className} bg-slate-900`}>{children}</body> 
    </html>
  );
}
